# -*- coding: utf-8 -*-
"""Exerc_Matemática_e_Estatística_com_Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FagKe91lbIBjYBRZynsrYZhHEfN5OG1b
"""

#Importar a pacote NumPy 
import numpy as np

"""##Exercícios

1) Construa e encontre as dimensões e número de elementos da matriz abaixo:

a)

$$A  = \begin{bmatrix}
1 & 11 & 7 \\
2 &  8 & 9
\end{bmatrix}$$
"""

#Digite seu código aqui
A = np.array(
      [[1, 11, 7], 
      [2, 8, 9]])

print('Dimensões Matriciais: {}'.format(A.shape))
print('Tamanho da Matriz: {}'.format(A.size))

"""2) Construa a matriz abaixo e exiba na tela. Altere os valores que estão nos índices Linhas e Coluna [1, 2] para 0 e [0,1] para o valor 999

b)

$$B  = \begin{bmatrix}
2 & 1 & 3 \\
1 & 2 & 5 \\
13 & 9 & 12
\end{bmatrix}$$
"""

#Digite seu código aqui
B = np.array(
    [[2, 1, 3],
    [1, 2, 5],
    [13, 9, 12]]
)

print('Matriz sem alteração \n', B, '\n')

B[1,2] = 0
B[0,1] = 999

print('Matriz com alteração dos valores \n',B)

"""3) Construa a matriz a seguir e crie uma nova matriz D a partir da tranposta de C:

c)

$$C  = \begin{bmatrix}
1 & 4 \\
2 & 4 \\
5 & 2
\end{bmatrix}$$
"""

#Digite seu código aqui

C = np.array([  [1, 4],
                [2, 4],
                [5, 2]])
print(C,'\n')

D = C.T
print('Transposta: \n', D)